name: Veracode Build

run-name: Vulnado Build

on:
  repository_dispatch:
    types: [vulnado-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.event.client_payload.repository.full_name }}
        ref: ${{ github.event.client_payload.sha }}
        token: ${{ github.event.client_payload.token }}
        event_name: ${{ github.event.action }}
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: oracle
    - name: Cache Maven Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
      
    - name: Identify the Artifact
      id: identify
      run: |
        jar_files=$(find target -name "*.jar" -type f -maxdepth 1 -exec basename {} \;)
        war_files=$(find target -name "*.war" -type f -maxdepth 1 -exec basename {} \;)
        ear_files=$(find target -name "*.ear" -type f -maxdepth 1 -exec basename {} \;)
        if [ ! -z "$jar_files" ]; then
          artifact_file=$jar_files
        elif [ ! -z "$war_files" ]; then
          artifact_file=$war_files
        elif [ ! -z "$ear_files" ]; then
          artifact_file=$ear_files
        else
          echo "no files found"
        fi
        echo $artifact_file
        echo "veracode_artifact=$artifact_file" >> $GITHUB_ENV
        
    - uses: actions/upload-artifact@v4
      with:
        name: veracode-artifact
        path: ${{ env.veracode_artifact }}
